"use client";

import { useEffect } from "react";
import type { Language } from "../types";
import { normalizeLanguage } from "../lib/i18n";

const createTranslationMap = (entries: ReadonlyArray<readonly [string, string]>) => {
  const map = new Map<string, string>();
  const duplicates = new Set<string>();
  for (const [key, value] of entries) {
    if (map.has(key)) duplicates.add(key);
    map.set(key, value);
  }
  if (duplicates.size && process.env.NODE_ENV !== "production") {
    console.warn("RuntimeTranslator duplicate keys:", Array.from(duplicates).join(", "));
  }
  return Object.fromEntries(map) as Record<string, string>;
};

const ruToEnTranslationEntries = [
  ["Создать привычку", "Create habit"],
  ["Привычки на день", "Daily habits"],
  ["Быстрая отметка без лишних шагов.", "Quick check-ins without extra steps."],
  ["Завершено", "Completed"],
  ["Требует внимания", "Needs attention"],
  ["Настроить экран Сегодня", "Customize Today screen"],
  ["Дневник дня", "Daily diary"],
  ["Календарь", "Calendar"],
  ["Аналитика", "Analytics"],
  ["Настройки", "Settings"],
  ["Управление", "Admin"],
  ["Цифры", "Numbers"],
  ["Прогноз дня", "Day forecast"],
  ["Запись дня", "Day note"],
  ["Что сделано", "What was done"],
  ["Что не сделано", "What was not done"],
  ["Что помогло", "What was done"],
  ["Что мешало", "What was not done"],
  ["История заметок", "Note history"],
  ["Настроить календарь и таблицу", "Customize calendar and table"],
  ["Оформление таблицы", "Table style"],
  ["Фильтр и видимость", "Filter and visibility"],
  ["Видимые элементы", "Visible elements"],
  ["Иконки отметок", "Check-in icons"],
  ["Встроенная лента и подсказки внутри приложения", "Built-in feed and hints inside the app"],
  ["Web Notifications в текущем браузере", "Web Notifications in the current browser"],
  ["Ежедневные и еженедельные письма", "Daily and weekly emails"],
  ["Сообщения через бота", "Messages through the bot"],
  ["Для будущего мобильного приложения", "For the future mobile app"],
  ["Тихие часы, частота и приоритеты доставки.", "Quiet hours, frequency and delivery priorities."],
  ["Все категории", "All categories"],
  ["Плотность сетки", "Grid density"],
  ["Клик по ячейке", "Cell click"],
  ["Активные", "Active"],
  ["Шаблоны", "Templates"],
  ["Изменить", "Edit"],
  ["В архив", "Archive"],
  ["Добавить привычку", "Add habit"],
  ["Библиотека привычек", "Habit library"],
  ["Отправить", "Send"],
  ["Отправляю...", "Sending..."],
  ["Отмена", "Cancel"],
  ["Удалить", "Delete"],
  ["Очистить", "Clear"],
  ["Всё", "All"],
  ["Undo", "Undo"],
  ["Профиль", "Profile"],
  ["Блоки", "Blocks"],
  ["Вид", "View"],
  ["Статусы", "Statuses"],
  ["Управление пользователями", "User management"],
  ["Пользователи, экспорт и глобальные настройки", "Users, export and global settings"],
  ["Список аккаунтов, полные email, привычки и отметки в календаре.", "Account list, full email, habits and calendar check-ins."],
  ["Вид", "View"],
  ["Пресеты меняют отображение, данные остаются на месте.", "Presets change the layout, data stays put."],
  ["Правая панель на ПК", "Right panel on desktop"],
  ["Дата рождения задаётся при регистрации и используется для прогноза и рекомендаций.", "Birth date is set during registration and powers forecasts and recommendations."],
  ["“Выполнено” всегда включено, остальные можно скрыть.", "\"Done\" is always on, the rest can be hidden."],
  ["Сколько истории показывать в календаре.", "How much calendar history to show."],
  ["Можно скрывать отдельные блоки только в мобильной версии экрана Сегодня.", "You can hide individual blocks only in the mobile Today screen."],
  ["Ориентир для самонаблюдения, без давления и без медицинских обещаний.", "A self-observation guide without pressure or medical promises."],
  ["Дата рождения берётся из профиля аккаунта, поэтому здесь её менять не нужно.", "Birth date comes from the account profile, so there is no need to change it here."],
  ["Числа Personal Day, Personal Month, Personal Year и Life Path считаются по дате рождения и выбранному дню.", "Personal Day, Personal Month, Personal Year and Life Path are calculated from the birth date and the selected day."],
  ["Сегодня на мобильном", "Today on mobile"],
  ["Мои пресеты", "My presets"],
  ["Экспорт / импорт", "Export / import"],
  ["Сбросить настройки", "Reset settings"],
  ["Контакты", "Contacts"],
  ["О проекте", "About"],
  ["Фон", "Background"],
  ["Панели", "Panels"],
  ["Текст", "Text"],
  ["Акцент", "Accent"],
  ["Выполнено", "Done"],
  ["Частично", "Partial"],
  ["Пропуск", "Skip"],
  ["Не выполнено", "Missed"],
  ["Запланировано", "Planned"],
  ["Классика", "Classic"],
  ["Неоновая доска", "Neon board"],
  ["Чек-лист недели", "Weekly checklist"],
  ["Сигнальные карточки", "Signal cards"],
  ["Мягкий", "Soft"],
  ["Мини", "Mini"],
  ["Таблица", "Table"],
  ["Контур", "Outline"],
  ["Сланец", "Slate"],
  ["Нейтральный", "Neutral"],
  ["Компактные плашки", "Compact chips"],
  ["Стеклянная сетка", "Glass grid"],
  ["Тепло-акцент", "Warm accent"],
  ["Гибридное кольцо", "Hybrid ring"],
  ["Как привычка", "Habit-like"],
  ["Приглушённые", "Muted"],
  ["Моно", "Mono"],
  ["Чередование", "Alternating"],
  ["Новый пароль администратора", "New admin password"],
  ["Сменить пароль администратора", "Change admin password"],
  ["Экспорт базы в JSON", "Export database as JSON"],
  ["Экспорт базы в SQL", "Export database as SQL"],
  ["Загружаю пользователей...", "Loading users..."],
  ["Имя", "Name"],
  ["Привычки", "Habits"],
  ["Отметки", "Check-ins"],
  ["Действия", "Actions"],
  ["Администратор", "Administrator"],
  ["Пользователь", "User"],
  ["Пользователи пока не загружены.", "No users loaded yet."],
  ["Текущий администратор:", "Current administrator:"],
  ["Глобальные настройки", "Global settings"],
  ["Применяются для новых пользователей после регистрации.", "Applied to new users after registration."],
  ["Взять текущие как дефолт", "Use current as default"],
  ["Сохранить дефолт", "Save defaults"],
  ["Календарь и таблица", "Calendar and table"],
  ["Все элементы оформления календаря и таблицы, как в пользовательском разделе.", "All calendar and table styling controls, just like in the user section."],
  ["Плотность", "Density"],
  ["Стартовый экран", "Start screen"],
  ["Тема календаря", "Calendar theme"],
  ["Оформление таблицы", "Table style"],
  ["Режим таблицы", "Table mode"],
  ["Цвет привычек", "Habit color"],
  ["Цвета таблицы", "Table colors"],
  ["Плотность сетки", "Grid density"],
  ["Клик по ячейке", "Cell click"],
  ["Правая панель", "Right panel"],
  ["Показывать выходные", "Show weekends"],
  ["Биоритмы", "Biorhythms"],
  ["Сегодня", "Today"],
  ["Дневник", "Diary"],
  ["Прогноз", "Forecast"],
  ["Транзит", "Transit"],
  ["Можно настроить базовую тему, стартовый экран и важные блоки по умолчанию.", "You can set the base theme, start screen and important blocks by default."],
  ["Почта для контактов", "Contact email"],
  ["Почта для контактов", "Contact email"],
  ["Адрес, на который приходят сообщения с формы контактов.", "Address that receives messages from the contact form."],
  ["Email получателя", "Recipient email"],
  ["Сохранить email", "Save email"],
  ["На странице контактов будет использован именно этот адрес.", "This address will be used on the Contacts page."],
  ["Один бот для всех пользователей системы. Привязка через /start.", "One bot for all system users. Link via /start."],
  ["Включить Telegram", "Enable Telegram"],
  ["Сохранить", "Save"],
  ["Проверить", "Check"],
  ["Снять webhook", "Remove webhook"],
  ["Отправить тест", "Send test"],
  ["Отключить", "Disable"],
  ["Статус", "Status"],
  ["Ключ для отправки формы контактов. Полный секрет не показывается.", "Key for sending contact form messages. The full secret is not shown."],
  ["Resend API key сохранён.", "Resend API key saved."],
  ["Ключ очищен, теперь будет использован fallback из env, если он задан.", "Key cleared; env fallback will be used if available."],
  ["Пока нет уведомлений для выбранного фильтра.", "No notifications for the selected filter yet."],
  ["Все", "All"],
  ["Новых", "New"],
  ["Отложено", "Snoozed"],
  ["Скрыто", "Hidden"],
  ["Оповещения", "Alerts"],
  ["Интерфейсные уведомления сейчас, внешние каналы и push-слоты на будущее.", "In-app notifications now, external channels and push slots for the future."],
  ["Каналы", "Channels"],
  ["Что доставлять и через какие каналы.", "What to deliver and through which channels."],
  ["Включить систему", "Enable system"],
  ["В интерфейсе", "In-app"],
  ["Браузер", "Browser"],
  ["Email", "Email"],
  ["Telegram", "Telegram"],
  ["Push", "Push"],
  ["Email для дайджестов", "Digest email"],
  ["Подключён", "Connected"],
  ["Не подключён", "Not connected"],
  ["Один бот для всех пользователей", "One bot for all users"],
  ["Полная ссылка подключения", "Full connect link"],
  ["Копировать ссылку", "Copy link"],
  ["Открыть ещё раз", "Open again"],
  ["активны", "active"],
  ["не активны", "inactive"],
  ["Настроение", "Mood"],
  ["Энергия", "Energy"],
  ["Стресс", "Stress"],
  ["Заметки", "Notes"],
  ["Тема", "Theme"],
  ["Период сетки", "Grid period"],
  ["Отображается:", "Shown:"],
  ["История календаря", "Calendar history"],
  ["Сохраняю...", "Saving..."],
  ["Открыть сегодня", "Open today"],
  ["Открыть дневник", "Open diary"],
  ["Тихие часы сейчас", "Quiet hours now"],
  ["мягкая пауза", "soft pause"],
  ["доставка открыта", "delivery open"],
  ["Тихие часы", "Quiet hours"],
  ["Частота", "Frequency"],
  ["Сразу", "Instant"],
  ["Ежедневно", "Daily"],
  ["Еженедельно", "Weekly"],
  ["Дайджест", "Digest"],
  ["День недели", "Weekday"],
  ["Пн", "Mon"],
  ["Вт", "Tue"],
  ["Ср", "Wed"],
  ["Чт", "Thu"],
  ["Пт", "Fri"],
  ["Сб", "Sat"],
  ["Вс", "Sun"],
  ["Только важное", "Important only"],
  ["Начало тишины", "Quiet hours start"],
  ["Конец тишины", "Quiet hours end"],
  ["Последняя проверка: сегодня", "Last check: today"],
  ["Последняя проверка:", "Last check:"],
  ["Обычная", "Basic"],
  ["Каждый день", "Every day"],
  ["Числовая", "Numeric"],
  ["Несколько раз в день", "Several times a day"],
  ["Не делать", "Avoid"],
  ["Простая отметка: сделал или не сделал.", "Simple check-in: done or not done."],
  ["Ежедневная привычка, которую хочется отмечать каждый день.", "An everyday habit you want to mark each day."],
  ["Подходит для шагов, минут, страниц или любого числа.", "Fits steps, minutes, pages or any number."],
  ["Несколько коротких повторов в день, например вода.", "Several short repeats a day, like water intake."],
  ["Успех дня — не сделать нежелательное действие.", "Success means not doing the unwanted action."],
  ["Запись или заметка считается выполнением.", "A note or entry counts as completed."],
  ["Спокойное движение без давления.", "Gentle movement without pressure."],
  ["Простая ежедневная привычка.", "Simple daily habit."],
  ["Отметить спокойный режим сна или подъёма.", "Mark a calm sleep or wake-up routine."],
  ["Без чисел, просто факт хорошего режима.", "No numbers, just the fact of a good routine."],
  ["Страницы, минуты или короткая сессия.", "Pages, minutes or a short session."],
  ["Числовая цель: например 20 минут или страниц.", "Numeric goal: for example 20 minutes or pages."],
  ["Короткая заметка о дне.", "A short note about the day."],
  ["Несколько минут тишины или дыхания.", "A few minutes of silence or breathing."],
  ["Числовая цель в минутах.", "Numeric goal in minutes."],
  ["Тренировка или короткая активность.", "Workout or short activity."],
  ["По умолчанию три раза в неделю.", "Default: three times a week."],
  ["Отметить день без нежелательной привычки.", "Mark a day without the unwanted habit."],
  ["Успех — нежелательное действие не произошло.", "Success: the unwanted action did not happen."],
  ["Пресет отображения", "Display preset"],
  ["Простой", "Simple"],
  ["Сбалансированный", "Balanced"],
  ["Журнал", "Journal"],
  ["Аналитический", "Analytical"],
  ["Стандартная", "standard"],
  ["Комфортная", "comfortable"],
  ["Компактная", "compact"],
  ["Имя бота", "Bot username"],
  ["Токен бота", "Bot token"],
  ["Секрет webhook", "Webhook secret"],
  ["Адрес получателя", "Recipient email"],
  ["Ключ API", "API key"],
  ["Разрешение", "Permission"],
  ["Вебхук", "Webhook"],
  ["Почта для дайджестов", "Digest email"],
  ["Источник", "Source"],
  ["Подключено пользователей", "Connected users"],
  ["Последняя доставка", "Last delivery"],
  ["admin", "Админ"],
  ["active", "Активный"],
  ["blocked", "Заблокированный"],
  ["JSON", "JSON"],
  ["SQL", "SQL"],
  ["Текущая отметка", "Current check-in"],
  ["нет отметки", "no check-in"],
  ["нет", "none"],
  ["Тип:", "Type:"],
  ["Цель:", "Goal:"],
  ["Статус:", "Status:"],
  ["Серия:", "Streak:"],
  ["Лучшая серия:", "Best streak:"],
  ["Последнее:", "Last:"],
  ["Значение / цель", "Value / goal"],
  ["Повторы / цель", "Repeats / goal"],
  ["Последние отметки", "Recent check-ins"],
  ["без заметки", "no note"],
  ["Заметка к отметке", "Check-in note"],
  ["Настроение в этой отметке", "Mood in this check-in"],
  ["История появится после первых отметок.", "History will appear after the first check-ins."],
  ["привычек выполнено", "habits completed"],
  ["Заметки на этот день пока нет.", "No notes for this day yet."],
  ["Открыть", "Open"],
  ["Настроение, энергия и стресс за день.", "Mood, energy and stress for the day."],
  ["Состояние сохраняется в дневнике за выбранную дату.", "The state is saved in the diary for the selected date."],
  ["Дата наблюдения", "Observation date"],
  ["дней с выполнения", "days since completion"],
  ["внимание", "attention"],
  ["Детали", "Details"],
  ["Редактировать", "Edit"],
  ["Последняя серия", "Last streak"],
  ["без выполнения", "without completion"],
  ["Пока нет истории выполнения.", "No completion history yet."],
  ["Добавьте запись за", "Add a note for"],
  ["Это поможет сохранить контекст дня без перегруза.", "This helps preserve the day's context without clutter."],
  ["Короткая заметка", "Short note"],
  ["Открыть обзор", "Open overview"],
  ["Можно включить Web Notifications для быстрых напоминаний.", "You can enable Web Notifications for quick reminders."],
  ["Разрешение запрашивается только в браузере и может быть отключено в любой момент.", "Permission is requested only in the browser and can be turned off at any time."],
  ["Проверить браузер", "Check browser"],
  ["Здоровье", "Health"],
  ["Состояние", "State"],
  ["Быт", "Home"],
  ["Фокус", "Focus"],
  ["Развитие", "Growth"],
  ["Самонаблюдение", "Non-daily"],
  ["Сон", "Sleep"],
  ["Спорт", "Sport"],
  ["Питание", "Nutrition"],
  ["Работа", "Work"],
  ["Отдых", "Rest"],
  ["Отношения", "Relationships"],
  ["Витамины", "Vitamins"],
  ["Ежедневный приём без лишней сложности.", "Daily intake without extra complexity."],
  ["Мягкий шаблон для важных мелочей.", "A gentle template for important small things."],
  ["Фрукты", "Fruit"],
  ["Добавить порцию фруктов в течение дня.", "Add a portion of fruit during the day."],
  ["Подходит для питания и рутины.", "Fits nutrition and routine."],
  ["Йога", "Yoga"],
  ["Спокойная практика для тела и внимания.", "A calm practice for body and attention."],
  ["Минуты, сессии или мягкий ритуал.", "Minutes, sessions or a gentle ritual."],
  ["Тренировка", "Workout"],
  ["Силовая, кардио или любая активная сессия.", "Strength, cardio or any active session."],
  ["Универсальный шаблон для спорта.", "A universal template for sport."],
  ["Не курить", "No smoking"],
  ["День без сигарет и лишних срывов.", "A day without cigarettes or slip-ups."],
  ["Успех — не закурить в течение дня.", "Success means not smoking during the day."],
  ["Чистить зубы", "Brush teeth"],
  ["Утренний и вечерний уход без пропусков.", "Morning and evening care without misses."],
  ["Ежедневная базовая привычка.", "A basic daily habit."],
  ["Зарядка", "Warm-up"],
  ["Короткая разминка для старта дня.", "A short warm-up to start the day."],
  ["Лёгкий шаблон на утро.", "A light template for the morning."],
  ["Покормить животное", "Feed pet"],
  ["Домашний ритуал без лишней сложности.", "A home ritual without extra complexity."],
  ["Подходит для повторов в течение дня.", "Fits repeats throughout the day."],
  ["Вода", "Water"],
  ["Несколько мягких отметок в течение дня.", "Several gentle check-ins throughout the day."],
  ["Хороший шаблон для привычек с повторениями.", "A good template for repeating habits."],
  ["Прогулка", "Walk"],
  ["План развития", "Roadmap"],
  ["Дорожная карта", "Roadmap"],
  ["AI и согласие", "AI and consent"],
  ["Подключение AI", "AI connection"],
  ["Отказ от ответственности", "Disclaimer"],
  ["Никакие данные не передаются по умолчанию третьим лицам и сторонним системам.", "No data is sent to third parties or external systems by default."],
  ["Анализ происходит только после согласия пользователя на предоставление данных искусственному интеллекту.", "Analysis happens only after the user consents to provide data to AI."],
  ["Любая предоставленная информация не является рекомендацией к действию и предоставлена только в ознакомительных целях.", "Any information provided is not a recommendation for action and is provided for informational purposes only."],
  ["Любое использование информации пользователь берет на свою ответственность, включая последствия, возникшие в результате применения данной информации.", "The user takes full responsibility for any use of the information, including consequences arising from applying it."],
  ["Пользователь принимает правила об отказе от претензий к владельцам проекта и использует информацию как есть.", "The user accepts the no-claims terms toward the project owners and uses the information as is."],
  ["План развития проекта", "Project roadmap"],
  ["AI анализирует записи дневника и календаря только после вашего явного согласия.", "AI analyzes diary and calendar entries only after your explicit consent."],
  ["По умолчанию данные не передаются ни третьим лицам, ни сторонним системам.", "By default, data is not shared with third parties or external systems."],
  ["Система может предложить выводы и варианты решений, но окончательное решение всегда остаётся за вами.", "The system can suggest insights and possible solutions, but the final decision always stays with you."],
  ["Любая информация в проекте предназначена только для ознакомления.", "Any information in the project is for informational purposes only."],
  ["Пользователь сам оценивает уместность применения информации и последствия её использования.", "The user evaluates the appropriateness of applying the information and the consequences of its use."],
  ["Проект и его владельцы не несут ответственности за действия, предпринятые на основе предоставленной информации.", "The project and its owners are not responsible for actions taken based on the provided information."],
  ["Вид", "View"],
  ["Пресеты меняют отображение, данные остаются на месте.", "Presets change the layout, data stays put."],
  ["Плотность", "Density"],
  ["Стартовый экран", "Start screen"],
  ["Правая панель на ПК", "Right panel on desktop"],
  ["Профиль", "Profile"],
  ["Дата рождения задаётся при регистрации и используется для прогноза и рекомендаций.", "Birth date is set during registration and powers forecasts and recommendations."],
  ["Статусы", "Statuses"],
  ["“Выполнено” всегда включено, остальные можно скрыть.", "\"Done\" is always on, the rest can be hidden."],
  ["Календарь", "Calendar"],
  ["Сколько истории показывать в календаре.", "How much calendar history to show."],
  ["Сегодня на мобильном", "Today on mobile"],
  ["Можно скрывать отдельные блоки только в мобильной версии экрана Сегодня.", "You can hide individual blocks only in the mobile Today screen."],
  ["Биоритмы", "Biorhythms"],
  ["Ориентир для самонаблюдения, без давления и без медицинских обещаний.", "A self-observation guide without pressure or medical promises."],
  ["Дата рождения берётся из профиля аккаунта, поэтому здесь её менять не нужно.", "Birth date comes from the account profile, so there is no need to change it here."],
  ["Числа Personal Day, Personal Month, Personal Year и Life Path считаются по дате рождения и выбранному дню.", "Personal Day, Personal Month, Personal Year and Life Path are calculated from the birth date and the selected day."],
  ["Цифры", "Numbers"],
  ["Мои пресеты", "My presets"],
  ["Название пресета", "Preset name"],
  ["Пока нет сохранённых пресетов.", "No saved presets yet."],
  ["Блоки", "Blocks"],
  ["Навигация", "Navigation"],
  ["Список привычек управляется на экране", "The habit list is managed on the"],
  ["Здесь остаются только общие режимы отображения и навигации.", "Only the shared display and navigation modes stay here."],
  ["Настройки оформления и видимости теперь живут в разделе календаря.", "Styling and visibility settings now live in the calendar section."],
  ["История, поля и компактность собраны в один блок.", "History, fields and compactness are grouped into one block."],
  ["Сбросить настройки", "Reset settings"],
  ["Экспорт / импорт", "Export / import"],
  ["Подготовить экспорт", "Prepare export"],
  ["Импортировать JSON", "Import JSON"],
  ["JSON для экспорта или импорта", "JSON for export or import"],
  ["Управление", "Management"],
  ["Управление пользователями", "User management"],
  ["Список аккаунтов, полные email, привычки и отметки в календаре.", "Account list, full email, habits and calendar check-ins."],
  ["Новый пароль администратора", "New admin password"],
  ["Сменить пароль администратора", "Change admin password"],
  ["Экспорт базы в JSON", "Export database as JSON"],
  ["Экспорт базы в SQL", "Export database as SQL"],
  ["Загружаю пользователей...", "Loading users..."],
  ["Имя", "Name"],
  ["Привычки", "Habits"],
  ["Отметки", "Check-ins"],
  ["Действия", "Actions"],
  ["Администратор", "Administrator"],
  ["Пользователь", "User"],
  ["Пользователи пока не загружены.", "No users loaded yet."],
  ["Текущий администратор:", "Current administrator:"],
  ["Все элементы оформления календаря и таблицы, как в пользовательском разделе.", "All calendar and table styling controls, just like in the user section."],
  ["Оформление таблицы", "Table style"],
  ["Режим таблицы", "Table mode"],
  ["Цвет привычек", "Habit color"],
  ["Цвета таблицы", "Table colors"],
  ["Плотность сетки", "Grid density"],
  ["Клик по ячейке", "Cell click"],
  ["Фильтр и видимость", "Filter and visibility"],
  ["Видимые элементы", "Visible elements"],
  ["Иконки отметок", "Check-in icons"],
  ["Включить биоритмы", "Enable biorhythms"],
  ["Включить цифры", "Enable numbers"],
  ["Включить Telegram", "Enable Telegram"],
  ["Почта для контактов", "Contact email"],
  ["Адрес, на который приходят сообщения с формы контактов.", "Address that receives messages from the contact form."],
  ["Email получателя", "Recipient email"],
  ["Сохранить email", "Save email"],
  ["На странице контактов будет использован именно этот адрес.", "This address will be used on the Contacts page."],
  ["Ключ для отправки формы контактов. Полный секрет не показывается.", "Key for sending the contact form. The full secret is not shown."],
  ["Resend API key сохранён.", "Resend API key saved."],
  ["Ключ очищен, теперь будет использован fallback из env, если он задан.", "Key cleared; env fallback will be used if available."],
  ["Telegram настройки", "Telegram settings"],
  ["Один бот для всех пользователей системы. Привязка через /start.", "One bot for all system users. Link via /start."],
  ["Имя бота", "Bot username"],
  ["Токен бота", "Bot token"],
  ["Секрет webhook", "Webhook secret"],
  ["Статус", "Status"],
  ["Подключено пользователей", "Connected users"],
  ["Последняя доставка", "Last delivery"],
  ["Сохранить", "Save"],
  ["Проверить", "Check"],
  ["Снять webhook", "Remove webhook"],
  ["Отправить тест", "Send test"],
  ["Отключить", "Disable"],
  ["Подключён", "Connected"],
  ["Не подключён", "Not connected"],
  ["Полная ссылка подключения", "Full connect link"],
  ["Копировать ссылку", "Copy link"],
  ["Открыть ещё раз", "Open again"],
  ["Пока нет уведомлений для выбранного фильтра.", "No notifications for the selected filter yet."],
  ["Все", "All"],
  ["Новых", "New"],
  ["Отложено", "Snoozed"],
  ["Скрыто", "Hidden"],
  ["Оповещения", "Alerts"],
  ["Интерфейсные уведомления сейчас, внешние каналы и push-слоты на будущее.", "In-app notifications now, external channels and push slots for the future."],
  ["Каналы", "Channels"],
  ["Что доставлять и через какие каналы.", "What to deliver and through which channels."],
  ["Включить систему", "Enable system"],
  ["В интерфейсе", "In-app"],
  ["Браузер", "Browser"],
  ["Email", "Email"],
  ["Telegram", "Telegram"],
  ["Push", "Push"],
  ["Email для дайджестов", "Digest email"],
  ["Тихие часы", "Quiet hours"],
  ["Частота", "Frequency"],
  ["Сразу", "Instant"],
  ["Ежедневно", "Daily"],
  ["Еженедельно", "Weekly"],
  ["Дайджест", "Digest"],
  ["Только важное", "Important only"],
  ["Начало тишины", "Quiet hours start"],
  ["Конец тишины", "Quiet hours end"],
  ["Последняя проверка: сегодня", "Last check: today"],
  ["Последняя проверка:", "Last check:"],
  ["Почта для контактов", "Contact email"],
  ["Фон", "Background"],
  ["Панели", "Panels"],
  ["Текст", "Text"],
  ["Акцент", "Accent"],
  ["День недели", "Weekday"],
  ["Пн", "Mon"],
  ["Вт", "Tue"],
  ["Ср", "Wed"],
  ["Чт", "Thu"],
  ["Пт", "Fri"],
  ["Сб", "Sat"],
  ["Вс", "Sun"],
  ["Обязательный статус", "Required status"],
  ["Значение / цель", "Value / goal"],
  ["Повторы / цель", "Repeats / goal"],
  ["Последние отметки", "Recent check-ins"],
  ["без заметки", "no note"],
  ["Заметка к отметке", "Check-in note"],
  ["Настроение в этой отметке", "Mood in this check-in"],
  ["История появится после первых отметок.", "History will appear after the first check-ins."],
  ["дней с выполнения", "days since completion"],
  ["внимание", "attention"],
  ["Детали", "Details"],
  ["Редактировать", "Edit"],
  ["Последняя серия", "Last streak"],
  ["без выполнения", "without completion"],
  ["Пока нет истории выполнения.", "No completion history yet."],
  ["Добавьте запись за", "Add a note for"],
  ["Это поможет сохранить контекст дня без перегруза.", "This helps preserve the day's context without clutter."],
  ["Короткая заметка", "Short note"],
  ["Открыть обзор", "Open overview"],
  ["Можно включить Web Notifications для быстрых напоминаний.", "You can enable Web Notifications for quick reminders."],
  ["Разрешение запрашивается только в браузере и может быть отключено в любой момент.", "Permission is requested only in the browser and can be turned off at any time."],
  ["Проверить браузер", "Check browser"],
  ["Сохранить дефолт", "Save defaults"],
  ["Взять текущие как дефолт", "Use current as default"],
  ["Глобальные настройки", "Global settings"],
  ["Применяются для новых пользователей после регистрации.", "Applied to new users after registration."],
  ["Вид", "View"],
  ["Пресеты меняют отображение, данные остаются на месте.", "Presets change the layout, data stays put."],
  ["Плотность", "Density"],
  ["Стартовый экран", "Start screen"],
  ["Правая панель на ПК", "Right panel on desktop"],
  ["Профиль", "Profile"],
  ["Дата рождения задаётся при регистрации и используется для прогноза и рекомендаций.", "Birth date is set during registration and powers forecasts and recommendations."],
  ["Статусы", "Statuses"],
  ["“Выполнено” всегда включено, остальные можно скрыть.", "\"Done\" is always on, the rest can be hidden."],
  ["Календарь", "Calendar"],
  ["Сколько истории показывать в календаре.", "How much calendar history to show."],
  ["Сегодня на мобильном", "Today on mobile"],
  ["Можно скрывать отдельные блоки только в мобильной версии экрана Сегодня.", "You can hide individual blocks only in the mobile Today screen."],
  ["Биоритмы", "Biorhythms"],
  ["Ориентир для самонаблюдения, без давления и без медицинских обещаний.", "A self-observation guide without pressure or medical promises."],
  ["Дата рождения берётся из профиля аккаунта, поэтому здесь её менять не нужно.", "Birth date comes from the account profile, so there is no need to change it here."],
  ["Цифры", "Numbers"],
  ["Числа Personal Day, Personal Month, Personal Year и Life Path считаются по дате рождения и выбранному дню.", "Personal Day, Personal Month, Personal Year and Life Path are calculated from the birth date and the selected day."],
  ["Мои пресеты", "My presets"],
  ["Название пресета", "Preset name"],
  ["Пока нет сохранённых пресетов.", "No saved presets yet."],
  ["Блоки", "Blocks"],
  ["Навигация", "Navigation"],
  ["Список привычек управляется на экране", "The habit list is managed on the"],
  ["Здесь остаются только общие режимы отображения и навигации.", "Only the shared display and navigation modes stay here."],
  ["Стартовый экран и режим фокуса настраиваются здесь же.", "The start screen and focus mode are configured here too."],
  ["Настройки оформления и видимости теперь живут в разделе календаря.", "Styling and visibility settings now live in the calendar section."],
  ["История, поля и компактность собраны в один блок.", "History, fields and compactness are grouped into one block."],
  ["Сбросить настройки", "Reset settings"],
  ["Экспорт / импорт", "Export / import"],
  ["Подготовить экспорт", "Prepare export"],
  ["Импортировать JSON", "Import JSON"],
  ["JSON для экспорта или импорта", "JSON for export or import"],
  ["Все элементы оформления календаря и таблицы, как в пользовательском разделе.", "All calendar and table styling controls, just like in the user section."],
  ["Оформление таблицы", "Table style"],
  ["Режим таблицы", "Table mode"],
  ["Цвет привычек", "Habit color"],
  ["Цвета таблицы", "Table colors"],
  ["Плотность сетки", "Grid density"],
  ["Клик по ячейке", "Cell click"],
  ["Фильтр и видимость", "Filter and visibility"],
  ["Видимые элементы", "Visible elements"],
  ["Иконки отметок", "Check-in icons"],
  ["Сегодня", "Today"],
  ["Дневник", "Diary"],
  ["Прогноз", "Forecast"],
  ["Транзит", "Transit"],
  ["Задать", "Set"],
  ["не задана", "not set"],
  ["Гость", "Guest"],
  ["Компактная", "Compact"],
  ["Стандартная", "Standard"],
  ["Комфортная", "Comfortable"],
  ["simple", "Simple"],
  ["balanced", "Balanced"],
  ["journal", "Journal"],
  ["analytical", "Analytical"],
  ["focus", "Focus"],
] as const;

const ruToEnTranslations = createTranslationMap(ruToEnTranslationEntries);
const attributes = ["placeholder", "title", "aria-label"];

function translateRoot(root: ParentNode, language: Language) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const textNodes: Text[] = [];
  while (walker.nextNode()) textNodes.push(walker.currentNode as Text);

  for (const node of textNodes) {
    const current = node.nodeValue || "";
    const trimmed = current.trim();
    if (!trimmed) continue;
    const nextText = language === "en" ? ruToEnTranslations[trimmed] : undefined;
    if (nextText && nextText !== trimmed) {
      const nextValue = current.replace(trimmed, nextText);
      if (node.nodeValue !== nextValue) node.nodeValue = nextValue;
    }
  }

  const elements = root instanceof Element ? [root, ...Array.from(root.querySelectorAll("*"))] : Array.from(root.querySelectorAll("*"));
  for (const element of elements) {
    for (const attr of attributes) {
      const current = element.getAttribute(attr);
      if (!current) continue;
      const trimmed = current.trim();
      const nextText = language === "en" ? ruToEnTranslations[trimmed] : undefined;
      if (nextText && nextText !== trimmed) {
        const nextValue = current.replace(trimmed, nextText);
        if (current !== nextValue) element.setAttribute(attr, nextValue);
      }
    }
  }
}

export function RuntimeTranslator({ language, selector = ".app" }: { language: Language; selector?: string }) {
  useEffect(() => {
    const normalized = normalizeLanguage(language);
    const root = document.querySelector(selector);
    if (!root) return;
    document.documentElement.lang = normalized;
    document.documentElement.dataset.language = normalized;
    if (normalized !== "en") return;
    translateRoot(root, normalized);
    const observer = new MutationObserver(() => translateRoot(root, normalized));
    observer.observe(root, { childList: true, subtree: true, characterData: true, attributes: true });
    return () => observer.disconnect();
  }, [language, selector]);

  return null;
}
